env:
  - PATH="/usr/lib/ccache:$PATH" CFLAGS="-g -O1 --coverage -fno-omit-frame-pointer -Wall -Wno-deprecated-declarations -Wno-macro-redefined -fno-optimize-sibling-calls -O1 -g -fstack-protector-all" LDFLAGS="--coverage"

language: c

cache:
  ccache: true
  pip: true
  directories:
    - "$HOME/.pyenv"

os:
#  - linux
  - osx

compiler:
#  - gcc
  - clang

dist: trusty

addons:
  apt:
    packages:
      - autotools-dev
      - autoconf
      - automake
      - libtool
      - ccache
      - libcap2-dev
      - libcmocka-dev
      - libdb-dev
      - libssl-dev
      - libxml2-dev
      - perl
      - pkg-config
      - zlib1g-dev
      - lcov

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew config; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update && brew bundle; fi
  - pip list --outdated --format=freeze | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 pip install -U
  - eval "$(pyenv init -)"
  - pyenv rehash
  - pip install cpp-coveralls
  - pyenv rehash
  - export PATH="/usr/local/opt/ccache/libexec:$PATH"

script:
  - ./configure --with-libtool --with-atf=/usr/local --enable-developer --with-libidn2=/usr/local --enable-warn-error --prefix=$HOME/.local --with-openssl=/usr/local/opt/openssl --without-make-clean
  - make
  - make unit
